name: Node.js Selenium Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-modules

      - name: Install Node.js dependencies
        run: npm install

      - name: Prepare artifacts
        run: |
          tar -czvf www-build.tar.gz ./package.json ./src ./tests
          ls -l

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: www-build
          path: www-build.tar.gz

  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: node:20
      ports:
        - 80:80
      options: --network-alias=testserver

    env:
      # Use HTTP for internal container communication (this is the fix)
      TEST_BASE_URL: http://testserver:80
      SELENIUM_HOST: http://selenium:4444/wd/hub
      # Add security-related environment variables
      NODE_ENV: test
      SELENIUM_TIMEOUT: 30000

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --shm-size=2gb

    steps:
      - name: Download built files
        uses: actions/download-artifact@v4
        with:
          name: www-build

      - name: Extract artifacts
        run: |
          tar -xzvf www-build.tar.gz
          ls -l

      - name: Install dependencies
        run: npm install

      - name: List files for debugging
        run: |
          echo "Current directory:"
          pwd
          echo "Files in the current directory:"
          ls -ltra .
          echo "Files in the src directory:"
          ls -ltra src/
          echo "Files in the tests directory:"
          ls -ltra tests/

      - name: Start Node.js server
        run: |
          # Start the server
          nohup node src/server.js > server.log 2>&1 &
          sleep 5  # Give the server some time to start

      - name: Show server logs
        run: cat server.log

      - name: Verify server is running
        run: |
          # Test server responsiveness with timeout
          timeout 10 curl -f http://localhost:80 || { 
            echo "Server failed to start"; 
            echo "Server logs:"; 
            cat server.log; 
            exit 1; 
          }

      - name: Wait for Selenium server to be up
        run: |
          echo "Waiting for Selenium server..."
          for i in {1..15}; do
            if curl -s --max-time 5 http://selenium:4444/wd/hub/status | grep -q "ready"; then
              echo "Selenium server is ready"
              break
            elif [ $i -eq 15 ]; then
              echo "Selenium server failed to start after 15 attempts"
              exit 1
            else
              echo "Attempt $i: Selenium server not ready yet, waiting..."
              sleep 3
            fi
          done

      - name: Verify Selenium server status
        run: |
          echo "Selenium server status:"
          curl -s http://selenium:4444/wd/hub/status || echo "Could not get Selenium status"

      - name: Debug network connectivity
        run: |
          echo "=== Network Debug Info ==="
          echo "Testing connectivity to selenium:4444..."
          nc -zv selenium 4444 || echo "Cannot connect to selenium:4444"
          echo "Testing connectivity to localhost:80..."
          nc -zv localhost 80 || echo "Cannot connect to localhost:80"
          echo "Current hostname:"
          hostname
          echo "Network interfaces:"
          ip addr show || ifconfig || echo "Could not show network info"

      - name: Run Selenium tests with HTTP only
        run: |
          echo "Starting Selenium tests with HTTP..."
          echo "Environment variables:"
          echo "SELENIUM_HOST: $SELENIUM_HOST"
          echo "TEST_BASE_URL: $TEST_BASE_URL"
          # Run tests with timeout and proper error handling
          timeout 300 node tests/SeleniumTest.mjs github || {
            echo "Tests failed or timed out"
            echo "Server logs:"
            cat server.log
            exit 1
          }

      - name: Cleanup and show final logs
        if: always()
        run: |
          echo "=== Final Server Logs ==="
          cat server.log || echo "No server logs found"
          echo "=== Test Environment Info ==="
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Container info:"
          df -h